specify min required version in hacs.json use release workflow to set it in const.py

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -26,6 +26,8 @@ jobs:
         run: |
           name=$(find custom_components/ -type d -maxdepth 1 | tail -n 1 | cut -d "/" -f2)
           echo "::set-output name=name::$name"
+          min_ha_version=$(jq -r '.homeassistant' ${{ github.workspace }}/hacs.json)
+          echo "::set-output name=min_ha_version::$min_ha_version"
       - name: 🖊️ Set version number
         run: |
           sed -i '/INTEGRATION_VERSION = /c\INTEGRATION_VERSION = "${{ steps.version.outputs.version }}"' \
@@ -33,6 +35,10 @@ jobs:
           jq '.version = "${{ steps.version.outputs.version }}"' \
             "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/manifest.json" > tmp \
             && mv -f tmp "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/manifest.json"
+      - name: 🖊️ Set min required HA version
+        run: |
+          sed -i '/MIN_REQUIRED_HA_VERSION = /c\MIN_REQUIRED_HA_VERSION = "${{ steps.information.outputs.min_ha_version }}"' \
+            "${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/const.py"
       - name: 👀 Validate data
         run: |
           if ! grep -q 'INTEGRATION_VERSION = "${{ steps.version.outputs.version }}"' ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/const.py; then
@@ -44,6 +50,11 @@ jobs:
           if [ "$manifestversion" != "${{ steps.version.outputs.version }}" ]; then
             echo "The version in custom_components/${{ steps.information.outputs.name }}/manifest.json was not correct"
             echo "$manifestversion"
+            exit 1
+          fi
+          if ! grep -q 'MIN_REQUIRED_HA_VERSION = "${{ steps.information.outputs.min_ha_version }}"' ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/const.py; then
+            echo "The MIN_REQUIRED_HA_VERSION in custom_components/${{ steps.information.outputs.name }}/const.py was not correct"
+            cat ${{ github.workspace }}/custom_components/${{ steps.information.outputs.name }}/const.py | grep MIN_REQUIRED_HA_VERSION
             exit 1
           fi
       - name: 📦 Create zip file for the integration
